[project]
name = "clary-quest"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "dotenv>=0.9.9",
    "transformers>=4.30.0",
    "pydantic>=2.0.0",
    "openai>=2.8.1",
    "pandas>=2.3.3",
    "notebook>=7.5.0",
]
